inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 4.2
  DisplayCopNames: true
  Include:
    - 'Capfile'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
  Exclude:
    - 'config/deploy.rb'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'lib/ext/activerecord/persistence.rb'
    - 'vendor/**/*'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/lib/partitioner/maven_spec.rb'

Lint/HandleExceptions:
  Exclude:
    - 'lib/git_repo.rb'

Lint/NestedMethodDefinition:
  Exclude:
    - 'app/jobs/enforce_timeouts_job.rb'

Lint/UselessAssignment:
  Exclude:
    - 'config/compass.rb'
    - 'spec/models/build_spec.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/partitioner/pants.rb'

Rails:
  Enabled: true

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  # will enable this after Ruby 3.0 is released
  Enabled: false

Style/GuardClause:
  # Personally disagree with this one. In certain situations not using a
  # GuardClause makes it more readable.
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false
