sudo: false
cache: bundler
language: ruby
rvm:
  - 2.4.3
  - 2.5.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:migrate
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec haml-lint app/views/
