# Do not commit production secrets to a public Git repository

test:
  github_oauth: "token-for-test"

development:
  github_oauth: "foo"

production:
  # overwrite this file on deployment with your Github OAuth token
  github_oauth:
