#!/usr/bin/env bash

echo Command: $0 $*
echo square/web is at `pwd`
echo
echo "Environment:"
env
echo

# set -ex: make script verbose and exit on first failed command
set -ex

gem install bundler --conservative
bundle check || bundle
bundle exec rake db:create db:schema:load RAILS_ENV=test
bundle exec rspec
